### ISSUE TITLE
generate error

### ISSUE THREAD

**Issue by qiwang97** [correttojs/graphql-codegen-apollo-cache#1]
my config:

```yml
# https://graphql-code-generator.com/docs/plugins/typescript-react-apollo

overwrite: true
schema: src/service/generated/schema.dev.graphql
documents: 'src/service/gql/*.gql'
hooks:
  afterAllFileWrite:
    - prettier --write "src/**/*.+(js|jsx|ts|tsx|json|yml|yaml|scss|css|md)"
generates:
  src/service/generated/component.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHOC: false
      withHooks: true
      withComponent: false
      skipTypename: true
      nonOptionalTypename: true
      addDocBlocks: false
  src/service/generated/cache.tsx:
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: ./component
    preset: import-types
    presetConfig:
      typesPath: ./component
    plugins:
      - graphql-codegen-apollo-cache

```

but the generated file has some error:
- more space
- unsorted import
- extra comma
- unexported type

```tsx
import * as Types from './component';

import * as Operations from './component';
import  { NormalizedCacheObject, defaultDataIdFromObject } from 'apollo-cache-inmemory';
import type { ApolloClient } from 'apollo-client';








export function readFragmentaction(cache: ApolloClient<NormalizedCacheObject>, fragmentId: string) {
                return cache.readFragment<Types.actionFragment>({
                    id: defaultDataIdFromObject({id: fragmentId, __typename: 'Action'}),
                    fragment: Operations.actionFragmentDoc,,
                    fragmentName: 'action',
                })
            };
export function readFragmentpageInfo(cache: ApolloClient<NormalizedCacheObject>, fragmentId: string) {
                return cache.readFragment<Types.pageInfoFragment>({
                    id: defaultDataIdFromObject({id: fragmentId, __typename: 'PaginationInfo'}),
                    fragment: Operations.pageInfoFragmentDoc,,
                    fragmentName: 'pageInfo',
                })
            };
export function readFragmentcluster(cache: ApolloClient<NormalizedCacheObject>, fragmentId: string) {
                return cache.readFragment<Types.clusterFragment>({
                    id: defaultDataIdFromObject({id: fragmentId, __typename: 'Group'}),
                    fragment: Operations.clusterFragmentDoc,,
                    fragmentName: 'cluster',
                })
            };
```
![image](https://user-images.githubusercontent.com/37304367/85116513-063cd800-b250-11ea-9ef2-4cc246616696.png)

extra info:
- node v12.16.1
- "@graphql-codegen/cli": "^1.15.4"
- "@graphql-codegen/schema-ast": "^1.15.4"
- "@graphql-codegen/typescript": "1.15.4"
- "@graphql-codegen/typescript-operations": "1.15.4"
- "@graphql-codegen/typescript-react-apollo": "1.15.4"
- "typescript": "~3.9.5",
